# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbe1ee668f34321984a43bb2ca789edfa139e3630ffcda98f98e972ccdd05e895118fba1df7334afde4e2a1cb42fff869154353a13229276a6db74293d4c8e41

test:
  secret_key_base: 2cf784085f0cb218de156249559f0b9cd81d7262195737f1859465d959238f8949df028e2add87da7a1f94c8f08860b3260ca03cd6496bbd549f0ba21b619326

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
